export default {
    ADD_POST: require("../assets/icons/add-post.png"),
    BACK: require("../assets/icons/back.png"),
    BELL_RINGER: require("../assets/icons/bell-ring.png"),
    COMMENT: require("../assets/icons/comments.png"),
    DOTS: require("../assets/icons/dots.png"),
    DOWN: require("../assets/icons/down.png"),
    FORWARD: require("../assets/icons/forward.png"),
    GRID_FILLED: require("../assets/icons/grid-filled.png"),
    GRID: require("../assets/icons/grid.png"),
    HOME_FILLED: require("../assets/icons/home-filled.png"),
    HOME: require("../assets/icons/home.png"),
    LIKE: require("../assets/icons/like.png"),
    LIKE_FILLED: require("../assets/icons/liked-filled.png"),
    MESSAGE: require("../assets/icons/message.png"),
    REELS_FILLED: require("../assets/icons/reels-filled.png"),
    REELS: require("../assets/icons/reels.png"),
    RIGHT: require("../assets/icons/right.png"),
    SAVED_FILLED: require("../assets/icons/saved-filled.png"),
    SAVED: require("../assets/icons/saved.png"),
    SEARCH_FILLED: require("../assets/icons/search-filled.png"),
    SEARCH: require("../assets/icons/search.png"),
    SHOPPING_CART_FILLED: require("../assets/icons/shopping-cart-filled.png"),
    SHOPPING_CART: require("../assets/icons/shopping-cart.png"),
    UP: require("../assets/icons/up.png"),
    LOGO_TEXT: require("../assets/images/logo.png"),
    LOGO_ICON: require("../assets/images/instagram.png"),
}